spring:
  application:
    name: hnn
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    # Render의 환경 변수에서 실제 DB 접속 정보를 가져옵니다.
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      connection-timeout: 30000
      max-lifetime: 900000
      validation-timeout: 3000

jwt:
  # Render의 환경 변수에서 JWT 비밀 키와 만료 시간을 가져옵니다.
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION_TIME}